# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-19 21:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('acl', '0002_usercategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=48)),
                ('status', models.CharField(choices=[(b'CONNECTED', b'Connected'), (b'DISCONNECTED', b'Disconnected'), (b'FAILED', b'Failed'), (b'FINISHED', b'Finished')], default=b'CONNECTED', max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name=b'date created')),
                ('end', models.DateTimeField(verbose_name=b'date ended')),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acl.UserList')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'db_table': 'staff_remoteconnection'
            },
        ),
    ]

    replaces = [('staff', '0003_remoteconnection')]
