# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-06-19 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acl', '0003_remoteconnection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remoteconnection',
            name='end',
            field=models.DateTimeField(blank=True, null=True, verbose_name=b'date ended'),
        ),
    ]

    replaces = [('staff', '0004_auto_20180619_1530')]
