# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-09 20:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acl', '0004_auto_20180619_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remoteconnection',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='acl.UserList'),
        ),
    ]

    replaces = [('staff', '0005_auto_20190409_1457')]
