# Generated by Django 2.2.4 on 2019-09-08 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acl', '0005_auto_20190409_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remoteconnection',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='remoteconnection',
            name='end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date ended'),
        ),
        migrations.AlterField(
            model_name='remoteconnection',
            name='status',
            field=models.CharField(choices=[('CONNECTED', 'Connected'), ('DISCONNECTED', 'Disconnected'), ('FAILED', 'Failed'), ('FINISHED', 'Finished')], default='CONNECTED', max_length=20),
        ),
        migrations.AlterField(
            model_name='userlist',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date created'),
        ),
        migrations.AlterField(
            model_name='userlist',
            name='modified',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date modified'),
        ),
    ]

    replaces = [('staff', '0006_auto_20190907_2214')]
