# Generated by Django 2.2.5 on 2019-12-20 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acl', '0007_announcement_staff_only'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ('priority',)},
        ),
    ]

    replaces = [('staff', '0008_auto_20191219_1940')]
