# Generated by Django 3.0.1 on 2019-12-30 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acl', '0008_auto_20191219_1940'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ('-staff_only', 'priority')},
        ),
        migrations.AlterField(
            model_name='announcement',
            name='priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]

    replaces = [('staff', '0009_auto_20191229_2336')]
