# Generated by Django 3.0.1 on 2019-12-30 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acl', '0009_auto_20191229_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='modal',
            field=models.BooleanField(default=False),
        ),
    ]

    replaces = [('staff', '0010_announcement_modal')]
