# Generated by Django 3.0.1 on 2019-12-31 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acl', '0010_announcement_modal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Announcement',
        ),
    ]

    replaces = [('staff', '0011_delete_announcement')]