# Generated by Django 3.0.1 on 2020-01-01 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acl', '0011_delete_announcement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserCategory',
        ),
    ]

    replaces = [('staff', '0012_delete_usercategory')]
