# Generated by Django 3.0.6 on 2020-07-15 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0056_populate_container_type'),
        ('acl', '0013_userlist_beamline'),
    ]

    operations = [
        migrations.RenameField(
            model_name='remoteconnection',
            old_name='list',
            new_name='userlist',
        ),
        migrations.AlterField(
            model_name='userlist',
            name='beamline',
            field=models.ManyToManyField(blank=True, related_name='access_lists', to='lims.Beamline'),
        ),
    ]

    replaces = [('staff', '0014_auto_20200715_0955')]