# Generated by Django 3.1.4 on 2020-12-02 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acl', '0016_auto_20201202_1327'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='remoteconnection',
            table=None,
        ),
        migrations.AlterModelTable(
            name='userlist',
            table=None,
        ),
    ]
