# Generated by Django 3.1.4 on 2020-12-02 22:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('acl', '0017_auto_20201202_1627'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RemoteConnection',
            new_name='Access',
        ),
    ]
