# Generated by Django 3.1.4 on 2020-12-02 22:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lims', '0077_auto_20201201_1535'),
        ('acl', '0018_auto_20201202_1629'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserList',
            new_name='AccessList',
        ),
    ]
