# Generated by Django 5.2.7 on 2025-10-07 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acl', '0019_auto_20201202_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='access',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='accesslist',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
