# Generated by Django 3.0.6 on 2020-07-17 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_facilitymode'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesstype',
            name='remote',
            field=models.BooleanField(default=False, verbose_name='Remote Access'),
        ),
    ]
