# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-12-06 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0002_auto_20171121_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='resolution',
            field=models.FloatField(blank=True, null=True, verbose_name=b'Desired Resolution'),
        ),
        migrations.AlterField(
            model_name='group',
            name='kind',
            field=models.IntegerField(choices=[(0, b'Native'), (1, b'MAD'), (2, b'SAD'), (3, b'S-SAD')], default=0, verbose_name=b'exp. type'),
        ),
        migrations.AlterField(
            model_name='group',
            name='plan',
            field=models.IntegerField(choices=[(0, b'Collect best'), (1, b'Collect first good'), (2, b'Screen and confirm'), (3, b'Screen and collect'), (4, b'Collect all')], default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='show_archives',
            field=models.BooleanField(default=True),
        ),
    ]
