# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-09 15:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0003_auto_20171206_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='lims.Container'),
        ),
        migrations.AlterField(
            model_name='container',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Sent'), (2, 'On-site'), (4, 'Returned'), (9, 'Archived')], default=0),
        ),
        migrations.AlterField(
            model_name='group',
            name='plan',
            field=models.IntegerField(choices=[(0, b'Collect best'), (1, b'Collect first good'), (2, b'Screen and confirm'), (4, b'Collect all')], default=0),
        ),
        migrations.AlterField(
            model_name='group',
            name='resolution',
            field=models.FloatField(blank=True, null=True, verbose_name=b'Desired Resolution (&#8491;)'),
        ),
    ]
