# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-09 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0004_auto_20180109_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
