# Generated by Django 2.2.4 on 2019-09-08 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0007_auto_20190907_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisreport',
            name='score',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
