# Generated by Django 2.2.5 on 2019-09-10 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0010_auto_20190909_2215'),
        ('lims', '0009_auto_20190909_0846'),
    ]

    operations = [
    ]
