# Generated by Django 2.2.5 on 2019-09-14 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0018_remove_containertype_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='containertype',
            name='locations',
            field=models.ManyToManyField(blank=True, related_name='types', through='lims.LocationCoord', to='lims.ContainerLocation'),
        ),
    ]
