# Generated by Django 2.2.5 on 2019-09-14 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0019_containertype_locations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='containerlocation',
            name='x',
        ),
        migrations.RemoveField(
            model_name='containerlocation',
            name='y',
        ),
    ]
