# Generated by Django 2.2.5 on 2019-09-17 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0020_auto_20190914_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='kind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='containers', to='lims.ContainerType'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.SlugField(),
        ),
    ]
