# Generated by Django 2.2.5 on 2019-11-09 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0021_auto_20190917_1434'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='sample_count',
        ),
    ]
