# Generated by Django 2.2.5 on 2019-11-10 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0024_tempsave_loc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='lims.ContainerLocation'),
        ),
        migrations.AlterUniqueTogether(
            name='sample',
            unique_together=set(),
        ),
    ]
