# Generated by Django 2.2.5 on 2019-11-11 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0032_populate_datatype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='kind_outgoing',
        ),
        migrations.AlterField(
            model_name='data',
            name='kind',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='datasets', to='lims.DataType', null=True),
        ),
    ]
