# Generated by Django 3.0.1 on 2019-12-27 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0036_update_data_num_frames'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='data',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='analysisreport',
            name='score',
            field=models.FloatField(default=0.0, null=True, verbose_name='Analysis Report Score'),
        ),
        migrations.AlterField(
            model_name='data',
            name='num_frames',
            field=models.IntegerField(default=1, verbose_name='Frame Count'),
        ),
    ]
