# Generated by Django 3.0.2 on 2020-01-20 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0046_fix_report_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dewar',
            name='beamline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dewars', to='lims.Beamline'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='kind',
            field=models.CharField(choices=[('snippet', 'Text'), ('video', 'Video'), ('image', 'Image')], default='snippet', max_length=20, verbose_name='Content Type'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='URL or Resource'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='carrier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='lims.Carrier'),
        ),
    ]
