# Generated by Django 3.0.2 on 2020-02-27 20:45

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0047_auto_20200120_1454'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDesignation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='project',
            name='designation',
            field=models.ManyToManyField(blank=True, to='lims.ProjectDesignation', verbose_name='Project Designation'),
        ),
    ]
