# Generated by Django 3.0.2 on 2020-03-03 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0050_data_frames_per_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='alias',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
