# Generated by Django 3.0.6 on 2020-05-19 22:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0052_auto_20200324_1631'),
    ]

    operations = [
        migrations.RenameField(
            model_name='beamline',
            old_name='simulated',
            new_name='active',
        ),
    ]
