# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-21 20:03
from __future__ import unicode_literals

from django.db import migrations, models
from basiclive.core import lims


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='frames',
            field=lims.models.FrameField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='key',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
