# Generated by Django 2.2.5 on 2019-09-10 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0008_auto_20190908_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='containerlocation',
            name='x',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='containerlocation',
            name='y',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='container',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contents', to='lims.ContainerLocation'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='container',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='samples', to='lims.Container'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='samples', to='lims.Group'),
        ),
    ]
