# Generated by Django 2.2.5 on 2019-09-11 04:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0011_merge_20190910_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='beamline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='datasets', to='lims.Beamline'),
        ),
        migrations.AlterField(
            model_name='data',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='datasets', to='lims.Group'),
        ),
        migrations.AlterField(
            model_name='data',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='data',
            name='sample',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='datasets', to='lims.Sample'),
        ),
        migrations.AlterField(
            model_name='data',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='datasets', to='lims.Session'),
        ),
    ]
