# Generated by Django 2.2.5 on 2019-09-14 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0015_auto_20190912_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationCoord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(default=0.0)),
                ('y', models.FloatField(default=0.0)),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coords', to='lims.ContainerType')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coords', to='lims.ContainerLocation')),
            ],
        ),
    ]
