# Generated by Django 2.2.5 on 2019-11-10 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0022_remove_group_sample_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='loc_name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
