# Generated by Django 2.2.5 on 2019-11-11 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0027_fix_cassette_coords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='loc_name',
        ),
        migrations.AlterField(
            model_name='data',
            name='kind',
            field=models.CharField(choices=[('MX_SCREEN', 'MX Screen'), ('MX_DATA', 'MX Data'), ('XRD_DATA', 'XRD Data'), ('RASTER', 'Raster'), ('XAS_SCAN', 'XAS Scan'), ('XRF_SCAN', 'XRF Scan'), ('MAD_SCAN', 'MAD Scan')], default='MX_SCREEN', max_length=20, verbose_name='Data type'),
        ),
    ]
