# Generated by Django 3.0.1 on 2020-01-01 00:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0043_populate_project_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='kind',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lims.ProjectType', verbose_name='Project Type'),
        ),
    ]
