# Generated by Django 3.0.1 on 2020-01-01 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0044_auto_20191231_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='kind',
            field=models.CharField(choices=[('snippet', 'Snippet'), ('video', 'Video'), ('image', 'Image')], default='snippet', max_length=20, verbose_name='Content Type'),
        ),
    ]
