# Generated by Django 3.0.4 on 2020-03-24 22:31

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0051_project_contract_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatype',
            name='metadata',
            field=jsonfield.fields.JSONField(default=[]),
        ),
    ]
