# Generated by Django 3.0.6 on 2020-06-01 15:56

from django.db import migrations
from django.core.management import call_command

def load_fixture(apps, schema_editor):
    """
    Populate Container Types for a base set of container layouts
    """

    ContainerType = apps.get_model('lims', 'ContainerType')
    db_alias = schema_editor.connection.alias

    # Create container types, if they do not already exist
    #if not ContainerType.objects.using(db_alias).all():
    #    call_command('loaddata', 'container-data', app_label='lims')


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0055_fix_container_locations'),
    ]

    operations = [
        migrations.RunPython(load_fixture)
    ]
