# Generated by Django 3.0.6 on 2020-08-10 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0056_populate_container_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysisreport',
            options={'ordering': ['created', '-score']},
        ),
        migrations.AlterModelOptions(
            name='data',
            options={'ordering': ['created'], 'verbose_name': 'Dataset'},
        ),
        migrations.AlterModelOptions(
            name='sample',
            options={'ordering': ['priority', 'container__name', 'location__name', 'name']},
        ),
        migrations.CreateModel(
            name='SSHKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('key', models.TextField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SSH Key',
            },
        ),
    ]
