# Generated by Django 3.1.3 on 2020-12-01 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0075_auto_20200923_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
