# Generated by Django 3.1.3 on 2020-12-02 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0056_populate_container_type'),
        ('lims', '0077_auto_20201201_1535'),
        ('lims', '0075_auto_20200923_0857'),
    ]

    operations = [
    ]
