# Generated by Django 3.1.3 on 2020-12-07 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0079_fix_datatype_templates'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dewar',
            new_name='Automounter',
        ),
    ]
