# Generated by Django 3.1.3 on 2020-12-07 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0080_auto_20201207_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automounter',
            name='beamline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layouts', to='lims.beamline'),
        ),
        migrations.AlterField(
            model_name='automounter',
            name='container',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beamlines', to='lims.container'),
        ),
    ]
