# Generated by Django 3.1.3 on 2021-01-11 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0083_request_requesttype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='shipment',
        ),
    ]
