# Generated by Django 3.1.3 on 2021-01-18 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0084_remove_request_shipment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='request',
            options={'ordering': ['priority'], 'verbose_name': 'Request'},
        ),
        migrations.RemoveField(
            model_name='group',
            name='absorption_edge',
        ),
        migrations.RemoveField(
            model_name='group',
            name='energy',
        ),
        migrations.RemoveField(
            model_name='group',
            name='kind',
        ),
        migrations.RemoveField(
            model_name='group',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='group',
            name='resolution',
        ),
    ]
