# Generated by Django 3.1.5 on 2021-01-28 16:52

import basiclive.core.lims.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0085_auto_20210118_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesttype',
            name='template',
            field=models.CharField(default='modal/form.html', max_length=100),
        ),
        migrations.AddField(
            model_name='sample',
            name='image',
            field=models.ImageField(blank=True, upload_to=basiclive.core.lims.models.get_sample_path),
        ),
    ]
