# Generated by Django 3.1.5 on 2021-01-28 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0087_requesttype_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesttype',
            name='layout',
            field=models.JSONField(blank=True, default={}),
            preserve_default=False,
        ),
    ]
