# Generated by Django 3.1.5 on 2021-02-01 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0088_requesttype_layout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='containertype',
            name='layout',
        ),
    ]
