# Generated by Django 3.1.4 on 2021-02-05 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0092_auto_20210205_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requesttype',
            name='edit_template',
            field=models.CharField(default='', max_length=100),
        ),
    ]
