# Generated by Django 3.1.4 on 2021-02-08 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lims', '0093_auto_20210205_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='requesttype',
            name='scope',
            field=models.CharField(default='UNLIMITED', max_length=15),
        ),
    ]
