# Generated by Django 3.1.3 on 2020-12-03 02:45

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lims', '0056_populate_container_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'lims_supportarea',
            }
        ),
        migrations.CreateModel(
            name='SupportRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('kind', models.CharField(choices=[('problem', 'Problem'), ('info', 'Info')], default='info', max_length=20, verbose_name='Kind')),
                ('comments', models.TextField(blank=True, null=True)),
                ('staff_comments', models.TextField(blank=True, null=True)),
                ('area', models.ManyToManyField(to='crm.SupportArea')),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='lims.Session')),
                ('staff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
                'db_table': 'lims_supportrecord',
            },
        ),
    ]

    replaces = [('lims', '0057_supportarea_supportrecord')]
