# Generated by Django 3.0.6 on 2020-07-17 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0059_auto_20200717_1318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='supportrecord',
            old_name='user',
            new_name='project',
        ),
    ]
    replaces = [
        ('lims', '0060_auto_20200717_1331'),
    ]
