# Generated by Django 3.0.6 on 2020-07-21 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0061_auto_20200717_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportarea',
            name='user_feedback',
            field=models.BooleanField(default=False),
        ),
    ]

    replaces = [
        ('lims', '0062_supportarea_user_feedback'),
    ]
