# Generated by Django 3.0.6 on 2020-07-24 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0065_auto_20200722_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportrecord',
            name='lost_time',
            field=models.FloatField(default=0.0, verbose_name='Time Lost (h)'),
        ),
        migrations.AlterField(
            model_name='userareafeedback',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impressions', to='crm.SupportArea'),
        ),
        migrations.AlterField(
            model_name='userareafeedback',
            name='feedback',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='crm.UserFeedback'),
        ),
        migrations.AlterField(
            model_name='userfeedback',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userfeedback',
            name='contact',
            field=models.BooleanField(default=False, verbose_name='Contact User'),
        ),
    ]

    replaces = [
        ('lims', '0066_auto_20200724_0845'),
    ]