# Generated by Django 3.0.6 on 2020-07-24 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0066_auto_20200724_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportrecord',
            name='lost_time',
            field=models.FloatField(default=0.0, verbose_name='Time Lost (hours)'),
        ),
        migrations.AlterField(
            model_name='userareafeedback',
            name='rating',
            field=models.IntegerField(choices=[(-2, 'Impressed'), (-1, 'Satisfied'), (1, 'Needs Improvement'), (2, 'Needs Urgent Attention'), (0, 'N/A')], default=0),
        ),
    ]

    replaces = [
        ('lims', '0067_auto_20200724_1323'),
    ]