# Generated by Django 3.0.6 on 2020-07-27 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0067_auto_20200724_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportrecord',
            name='areas',
            field=models.ManyToManyField(blank=True, related_name='help', to='crm.SupportArea'),
        ),
        migrations.AlterField(
            model_name='userareafeedback',
            name='rating',
            field=models.IntegerField(choices=[(-2, 'Needs Urgent Attention'), (-1, 'Needs Improvement'), (1, 'Satisfied'), (2, 'Impressed'), (0, 'N/A')], default=0),
        ),
        migrations.AlterField(
            model_name='userfeedback',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback', to='lims.Session'),
        ),
    ]

    replaces = [
        ('lims', '0068_auto_20200727_1554'),
    ]