# Generated by Django 3.0.6 on 2020-07-31 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0068_auto_20200727_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportarea',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]

    replaces = [
        ('lims', '0069_auto_20200731_1005'),
    ]