# Generated by Django 3.0.6 on 2020-07-31 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0069_auto_20200731_1005'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackScale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worst', models.CharField(max_length=25, verbose_name='-2')),
                ('worse', models.CharField(max_length=25, verbose_name='-1')),
                ('better', models.CharField(max_length=25, verbose_name='1')),
                ('best', models.CharField(max_length=25, verbose_name='2')),
            ],
            options={
                'db_table': 'lims_feedbackscale',
            }
        ),
        migrations.AlterField(
            model_name='userareafeedback',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userareafeedback',
            name='scale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='areas', to='crm.FeedbackScale'),
        ),
    ]

    replaces = [
        ('lims', '0070_auto_20200731_1033'),
    ]