# Generated by Django 3.0.6 on 2020-07-31 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0070_auto_20200731_1033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userareafeedback',
            name='scale',
        ),
        migrations.AddField(
            model_name='supportarea',
            name='scale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='areas', to='crm.FeedbackScale'),
        ),
    ]

    replaces = [
        ('lims', '0071_auto_20200731_1044'),
    ]
