# Generated by Django 3.0.6 on 2020-10-20 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0072_feedbackscale_statement'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportarea',
            name='external',
            field=models.BooleanField(default=False, verbose_name="External (out of the beamline's control)"),
        ),
    ]

    replaces = [
        ('lims', '0076_auto_20201020_1529'),
    ]