# Generated by Django 3.1.3 on 2020-12-02 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0076_auto_20201020_1529'),
        ('crm', '0072_feedbackscale_statement'),
    ]

    operations = [
    ]

    replaces = [
        ('lims', '0077_merge_20201202_1619'),
    ]
