# Generated by Django 3.0.2 on 2020-01-14 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0003_auto_20200113_1802'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publication',
            name='contributors',
        ),
        migrations.AddField(
            model_name='journal',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='journals', to='publications.SubjectArea'),
        ),
        migrations.DeleteModel(
            name='Affiliation',
        ),
        migrations.DeleteModel(
            name='Contributor',
        ),
        migrations.DeleteModel(
            name='Institution',
        ),
    ]
