# Generated by Django 3.0.2 on 2020-01-14 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0007_auto_20200114_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='short_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
