# Generated by Django 3.0.2 on 2020-01-28 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0012_auto_20200117_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funder',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='metrics',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='publication', to='publications.Metric'),
        ),
    ]
