# Generated by Django 3.0.2 on 2020-01-14 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0004_auto_20200113_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='publisher',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='short_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='journal',
            name='title',
            field=models.TextField(),
        ),
    ]
