# Generated by Django 3.0.2 on 2020-01-14 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0006_auto_20200114_0700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funder',
            name='name',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='publisher',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='main_title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
