# Generated by Django 3.0.2 on 2020-01-16 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0008_auto_20200114_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journalprofile',
            name='scimago_rank',
        ),
        migrations.AddField(
            model_name='journalprofile',
            name='sjr_quartile',
            field=models.SmallIntegerField(default=4, null=True, verbose_name='SJR-Quartile'),
        ),
        migrations.AddField(
            model_name='journalprofile',
            name='sjr_rank',
            field=models.FloatField(default=0.0, null=True, verbose_name='SJR-Rank'),
        ),
        migrations.AlterField(
            model_name='journalprofile',
            name='h_index',
            field=models.IntegerField(default=1.0, null=True, verbose_name='H-Index'),
        ),
        migrations.AlterField(
            model_name='journalprofile',
            name='impact_factor',
            field=models.FloatField(default=0.0, null=True, verbose_name='Impact Factor'),
        ),
    ]
