# Generated by Django 3.0.2 on 2020-01-17 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0011_auto_20200117_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='metrics',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='publications.JournalProfile'),
        ),
        migrations.AddField(
            model_name='publication',
            name='metrics',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='publications.Metric'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='all_metrics', to='publications.Publication'),
        ),
    ]
